apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      service: service-a

  template:
    metadata:
      labels:
        service: service-a

    spec:
      containers:
        - name: service-a-container
          image: abuelnaga0/metrics-exposing-app-service-a:v1.0.0
          ports:
            - containerPort: 3001
              protocol: TCP
              name: http

            - containerPort: 3001
              protocol: TCP
              name: metrics

          env:
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              value: "http://otel-collector-collector.tracing.svc.cluster.local:14268/api/traces"

            - name: SERVICE_B_URI
              value: "http://service-b.default.svc.cluster.local"
