apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

labels:
  - pairs:
      app: metrics-exposing-app

    includeSelectors: true
    includeTemplates: true

resources:
  - service-a/deployment.k8s.yaml
  - service-a/service.k8s.yaml
  - service-b/deployment.k8s.yaml
  - service-b/service.k8s.yaml